#!/bin/bash

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged --relative=api --name-only | cat)
if [[ "${DIFF}" ]]; then
  # Run GrumPHP
  (cd "./docker" && echo "${DIFF}" | docker compose exec -i symfony bash -c "'php' 'vendor/bin/grumphp' 'git:pre-commit' '--skip-success-output'")
else
  echo "no php file";
  exit 0;
fi

# Validate exit code of above command
RC=$?
if [ "$RC" != 0 ]; then
  exit $RC;
fi

# Clean exit:
exit 0;
